RD-34 First tests of AddNewStationForm component
monikahenschke/radio-app-react pull request #36
Opened 2022-06-06 17:05 UTC by monikahenschke

2022-06-09 21:53 UTC, patryk-bernasiewicz requested changes
There's 4 failing test suites, apparently some of the test still try to use the `Layout` component and the `Modal` still tries to use its internal state

![image](https://user-images.githubusercontent.com/10709214/172951626-bd74f96c-8f0e-4ac3-9b4c-d28ba83fb211.png)

2022-06-09 21:56 UTC, patryk-bernasiewicz commented
I just noticed you fixed the tests in RD-38 - you can rebase this branch with RD-38 and then the tests should pass

2022-06-13 10:43 UTC, monikahenschke commented
I did git rebase with RD-34, and changed the base branch to RD-33, so should I do 'git rebase' on main with RD-33 and RD-36? :)

2022-06-14 16:40 UTC, patryk-bernasiewicz approved these changes

2022-06-14 17:07 UTC, merged